name: flutter_bloc_inject
description: Flutter denpendency Injection to Bloc patern apps
version: 0.0.3
author: Diefferson Santos <diefferson.sts@gmail.com>
homepage: https://github.com/diefferson/flutter_bloc_inject

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: