name: flutter_bloc_inject
description: Flutter Dependency Injection to apps with Bloc pattern, to provide an easy injection pattern and powerful
version: 1.0.1
author: Diefferson Santos <diefferson.sts@gmail.com>
homepage: https://github.com/diefferson/flutter_bloc_inject

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: